#!/usr/bin/env python3
"""
dump_ui_keys.py — inventory all 7 root menus and every TB_* toolbar constant.

Outputs tools/ui-keys.md for use when authoring mode allowlists.

Usage (from repo root):
    QT_QPA_PLATFORM=offscreen .venv/bin/python3 tools/dump_ui_keys.py
"""
import os
import sys
import types

# ── bootstrap: must be run from bin/ so Code.__init__ sets paths correctly ──
sys.argv = ["LucasR.py"]
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "bin"))
sys.path.insert(0, os.getcwd())

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PySide6 import QtWidgets
app = QtWidgets.QApplication.instance() or QtWidgets.QApplication(sys.argv)

import Code
from Code.Config import Configuration
from Code.QT import IconosBase
from Code.Main import InitApp

# ── init config first (start() calls Translate.install internally) ───────────
Code.configuration = Configuration.Configuration("")
Code.configuration.start()
InitApp.init_app_style(app, Code.configuration)
IconosBase.icons.reset(Code.configuration.x_style_icons)

from Code.QT import Piezas
Code.all_pieces = Piezas.AllPieces()

# ── minimal stub so menus don't crash on procesador.main_window ──────────────
stub_window = types.SimpleNamespace(
    key_video="maind",
    accept=lambda: None,
    final_processes=lambda: None,
)
stub_procesador = types.SimpleNamespace(
    main_window=stub_window,
    configuration=Code.configuration,
    manager=None,
    board=None,
)
Code.procesador = stub_procesador

# ── import all 7 menu classes ─────────────────────────────────────────────────
from Code.Menus import (
    PlayMenu, TrainMenu, CompeteMenu, ToolsMenu,
    EnginesMenu, OptionsMenu, InformationMenu, BaseMenu,
)

MENUS = [
    PlayMenu.PlayMenu,
    TrainMenu.TrainMenu,
    CompeteMenu.CompeteMenu,
    ToolsMenu.ToolsMenu,
    EnginesMenu.EnginesMenu,
    OptionsMenu.OptionsMenu,
    InformationMenu.InformationMenu,
]

# ── TB_* constants ────────────────────────────────────────────────────────────
from Code.Main.WBase import WBase
from Code.Base import Constantes

tb_names = {v: k for k, v in vars(Constantes).items() if k.startswith("TB_")}
dic_tb_labels = {k: v[0] for k, v in WBase.dic_opciones_tb().items()}

# ── recursive menu walker ─────────────────────────────────────────────────────
def walk(items, path=""):
    rows = []
    for item in items:
        if isinstance(item, BaseMenu.SubMenu):
            sub_path = f"{path}/{item.label}" if path else item.label
            rows += walk(item.li_options, sub_path)
        elif isinstance(item, BaseMenu.Option):
            rows.append((item.key, item.label, path or "(root)"))
    return rows

# ── build output ──────────────────────────────────────────────────────────────
lines = ["# Caissa UI Key Inventory", "", "Generated by `tools/dump_ui_keys.py`. Re-run after upstream updates.", ""]

# TB_* table
lines += ["## Toolbar constants (`TB_*`)", "", "| Constant | Value | Label |", "|---|---|---|"]
for val in sorted(tb_names):
    name = tb_names[val]
    label = dic_tb_labels.get(val, "—")
    lines.append(f"| `{name}` | {val} | {label} |")
lines.append("")

# Root toolbar (li_opciones_inicio)
from Code.Base.Constantes import (TB_QUIT, TB_PLAY, TB_TRAIN, TB_COMPETE,
                                   TB_TOOLS, TB_ENGINES, TB_OPTIONS, TB_INFORMATION)
inicio = [TB_QUIT, TB_PLAY, TB_TRAIN, TB_COMPETE, TB_TOOLS, TB_ENGINES, TB_OPTIONS, TB_INFORMATION]
lines += ["## Main window toolbar (`li_opciones_inicio`)", ""]
lines += [f"- `{tb_names.get(k, k)}` — {dic_tb_labels.get(k, '?')}" for k in inicio]
lines.append("")

# Per-menu option tables
lines.append("## Menu option keys")
lines.append("")

for MenuClass in MENUS:
    try:
        menu = MenuClass(stub_procesador)
        menu.add_options()
        rows = walk(menu.li_options)
        lines.append(f"### {MenuClass.name}")
        lines.append("")
        lines.append("| Key | Label | Path |")
        lines.append("|---|---|---|")
        for key, label, path in rows:
            lines.append(f"| `{key}` | {label} | {path} |")
        lines.append("")
    except Exception as exc:
        lines.append(f"### {MenuClass.name}")
        lines.append(f"\n> ⚠️ Error during add_options(): `{exc}`\n")

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ui-keys.md")
with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Written: {out_path}")
print(f"  {sum(1 for l in lines if l.startswith('| `'))} option rows")
